---
title: "📦 Installation"
subtitle: "VIMuRe v0.1 (latest)"
---

VIMuRe is available in both R and Python. The R implementation is a wrapper around the Python implementation. Both packages are in active development and are not yet on CRAN or PyPI. Use the installation instructions below to install the latest development version.

::: callout-note

## 📢 Note

If your preferred language is R, we would like to hear from you. Please add a message [to this discussion](https://github.com/latentnetworks/vimure/discussions/66) to tell us whether you would like to see an easier installation process for R.
:::

Choose your language:


::: panel-tabset

# R

<details><summary>Step 01: Install `reticulate`</summary>

## Step 01: Install `reticulate`

1. Open your R console and type the following command:

    ```r
    install.packages("reticulate")
    ```

2. Check if `reticulate` has a valid Python installation by running the following command:

    ```r
    reticulate::py_config()
    ```

    You should see something like the following if you have a valid Python installation identified by `reticulate`:

    ```r
    python:         ...path..to.../python/r-reticulate/bin/python
    libpython:      ...path..to.../r-reticulate/lib/libpython3.8.so
    pythonhome:     ...path..to.../r-reticulate:/home/jonathan/Workspace/vimure/renv/python/r-reticulate
    version:        3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55)  [GCC 11.3.0]
    numpy:          ...path..to.../python/r-reticulate/lib/python3.8/site-packages/numpy
    numpy_version:  1.24.2
    ```

    If instead, you see something like the following, type `Y` and press enter to install [miniconda](https://docs.conda.io/en/latest/miniconda.html):

    ```r
    No non-system installation of Python could be found.
    Would you like to download and install Miniconda?
    Miniconda is an open source environment management system for Python.
    See https://docs.conda.io/en/latest/miniconda.html for more details.

    Would you like to install Miniconda? [Y/n]: Y
    ```

3. Close the R session and open it again to make sure the changes take effect.

::: {.callout-note collapse="true"}
## Why do I need this package?

- Our core code is written in python, so we use `reticulate` to integrate our model in R. This package allows you to use Python within your R session in a seamless, high-performance interoperable way. 

- `reticulate` will look for the python installed on your computer. If for some reason it cannot find it, you may be prompted to download and install [miniconda](https://docs.conda.io/en/latest/miniconda.html). 

    - [miniconda](https://docs.conda.io/en/latest/miniconda.html) is the recommended installation method for most users, as it is easier to ensure that the newly installed python is isolated from other python installs you have in your system. 

    - If you initially declined the [miniconda](https://docs.conda.io/en/latest/miniconda.html) installation prompt, you can later manually install [miniconda](https://docs.conda.io/en/latest/miniconda.html) by running `reticulate::install_miniconda()`.

:::

<p style="margin-bottom: 2rem;"></p>
</details>


<details><summary>Step 02: Install the latest `vimure` (v0.1) </summary>

## Step 02: Install the latest `vimure` (v0.1)

In your R console, type the following commands:

```r
require(devtools)
devtools::install_github("latentnetworks/vimure", subdir="src/R", ref="develop")
```

Check out [devtools](https://devtools.r-lib.org/) package documentation if you are not familiar with it.

<p style="margin-bottom: 2rem;"></p>

</details>

<details><summary>Step 03: Install the Python package</summary>

## Step 03: Install the Python package 

You **must** install the python package before using the R package. This is because the R package is a wrapper around the Python package. You can do this without leaving R, though. Just type the following command in your R console:

```r
require(vimure)
vimure::install_vimure()
```

If you are not using RStudio, i.e., you are using R in the terminal, you may need to restart your R session after installing the Python package.

Not a fan of having to do this python setup? Please add a message [to this discussion](https://github.com/latentnetworks/vimure/discussions/66) to tell us you would like to see an easier installation process for R.

<p style="margin-bottom: 2rem;"></p>

</details>

<details><summary>Step 04: Check the installation</summary>

### Step 04: Check the installation

To confirm that the installation was successful, run the following command:

```r
library(vimure)
vimure::vm_config()
```

You should see something like the following:

```r
#> Loaded vimure version
#> Vimure v (...)
#> Python v3.x (...)
```

</details>


# Python

`vimure` is not yet available on PyPI, so to install the latest development version, follow the instructions below.

Install the latest `vimure` (v0.1) with the following command:

```bash
pip install "git+https://github.com/latentnetworks/vimure.git#egg=vimure&subdirectory=src/python/"
```

This Python package was tested on Python >= 3.6, and it is expected to work fine in all OSes.

Read more about the Python setup for development [here](https://github.com/latentnetworks/vimure/blob/develop/src/python/README.md).

:::
