---
title: "📚 Python package documentation"
subtitle: "VIMuRe v0.1 (latest)"
---
Module `vimure.test.test_synthetic`

## Classes

`class TestBaseSyntheticNetwork`

### Subclasses


* [TestMultitensor](#vimure.test.test_synthetic.TestMultitensor "vimure.test.test_synthetic.TestMultitensor")
* [TestStandardSBM](#vimure.test.test_synthetic.TestStandardSBM "vimure.test.test_synthetic.TestStandardSBM")


### Methods

`def check_objects(self, synth_net)`

`class TestDegreeCorrectedSBM`

### Ancestors


* [TestStandardSBM](#vimure.test.test_synthetic.TestStandardSBM "vimure.test.test_synthetic.TestStandardSBM")
* [TestBaseSyntheticNetwork](#vimure.test.test_synthetic.TestBaseSyntheticNetwork "vimure.test.test_synthetic.TestBaseSyntheticNetwork")


### Methods

`def test_degree_correction_was_indeed_applied(self)`

Does the Y matrix also change when we change exp_in and exp_out?

### Inherited members


* `**[TestStandardSBM](#vimure.test.test_synthetic.TestStandardSBM "vimure.test.test_synthetic.TestStandardSBM")**`:
	+ [`setup_class`](vimure.#vimure.test.test_synthetic.TestStandardSBM.setup_class)
	+ [`test_yields_appropriate_affinity_matrix`](vimure.#vimure.test.test_synthetic.TestStandardSBM.test_yields_appropriate_affinity_matrix)
	+ [`test_yields_appropriate_objects`](vimure.#vimure.test.test_synthetic.TestStandardSBM.test_yields_appropriate_objects)

`class TestMultitensor`

### Ancestors


* [TestBaseSyntheticNetwork](#vimure.test.test_synthetic.TestBaseSyntheticNetwork "vimure.test.test_synthetic.TestBaseSyntheticNetwork")


### Static methods

`def setup_class()`

Creates a single Multitensor instance object to be shared by tests in this class

### Methods

`def test_yields_appropriate_objects(self)`

CHECK matrices and objects have the right types and shapes and values

`class TestStandardSBM`

### Ancestors


* [TestBaseSyntheticNetwork](#vimure.test.test_synthetic.TestBaseSyntheticNetwork "vimure.test.test_synthetic.TestBaseSyntheticNetwork")


### Subclasses


* [TestDegreeCorrectedSBM](#vimure.test.test_synthetic.TestDegreeCorrectedSBM "vimure.test.test_synthetic.TestDegreeCorrectedSBM")


### Static methods

`def setup_class()`

Creates a single StandardSBM instance object to be shared by tests in this class

### Methods

`def test_yields_appropriate_affinity_matrix(self)`

Focusing on matrix w: did it yield expected values?

`def test_yields_appropriate_objects(self)`

CHECK matrices and objects have the right types and shapes and values

# Index

* ### Super-module


	+ [`vimure.test`](vimure.index.html)
* ### [Classes](#header-classes)


	+ #### [`TestBaseSyntheticNetwork`](vimure.#vimure.test.test_synthetic.TestBaseSyntheticNetwork)
	
	
		- [`check_objects`](vimure.#vimure.test.test_synthetic.TestBaseSyntheticNetwork.check_objects)
	+ #### [`TestDegreeCorrectedSBM`](vimure.#vimure.test.test_synthetic.TestDegreeCorrectedSBM)
	
	
		- [`test_degree_correction_was_indeed_applied`](vimure.#vimure.test.test_synthetic.TestDegreeCorrectedSBM.test_degree_correction_was_indeed_applied)
	+ #### [`TestMultitensor`](vimure.#vimure.test.test_synthetic.TestMultitensor)
	
	
		- [`setup_class`](vimure.#vimure.test.test_synthetic.TestMultitensor.setup_class)
		- [`test_yields_appropriate_objects`](vimure.#vimure.test.test_synthetic.TestMultitensor.test_yields_appropriate_objects)
	+ #### [`TestStandardSBM`](vimure.#vimure.test.test_synthetic.TestStandardSBM)
	
	
		- [`setup_class`](vimure.#vimure.test.test_synthetic.TestStandardSBM.setup_class)
		- [`test_yields_appropriate_affinity_matrix`](vimure.#vimure.test.test_synthetic.TestStandardSBM.test_yields_appropriate_affinity_matrix)
		- [`test_yields_appropriate_objects`](vimure.#vimure.test.test_synthetic.TestStandardSBM.test_yields_appropriate_objects)

Generated by [pdoc 0.10.0](https://pdoc3.github.io/pdoc "pdoc: Python API documentation generator").

