---
title: "📚 Python package documentation"
subtitle: "VIMuRe v0.1 (latest)"
---
Module `vimure.test.test_model`

## Functions

`def check_final_parameters(model, net_obj)`

Latent Variables - Parameter rho

## Classes

`class TestInferredModel`

### Static methods

`def setup_class()`

### Methods

`def check_output(self, Y, model)`

`def test_fixed_threshold(self)`

`def test_heuristic_threshold(self)`

`def test_non_implemented_method(self)`

`def test_rho_max(self)`

`def test_rho_mean(self)`

`def test_sample_Y(self)`

`class TestVimureRealData`

### Methods

`def test_data_as_edgelist(self, karnataka_edgelist_vil1_money)`

`def test_internal_api(self, karnataka_edgelist_vil1_money)`

`class TestVimureWithRandomNetworks`

Tests of the VimureModel class

### Methods

`def test_vimure_model_extreme_scenarios_over_reporting(self)`

Ensures that the model achieves F1-score near 1.0 on a known
extreme scenario (10% exaggerators over-reporting)

`def test_vimure_model_extreme_scenarios_over_reporting_dense(self)`

Ensures that the model achieves F1-score near 1.0 on a known
extreme scenario (10% exaggerators over-reporting)

`def test_vimure_model_extreme_scenarios_under_reporting(self)`

Ensures that the model achieves F1-score near 1.0 on a known
extreme scenario (10% exaggerators under-reporting)

`def test_vimure_model_issues_appropriate_warnings(self)`

Tests the VimureModel class with a known synthetic network

`def test_vimure_model_with_standard_sbm(self)`

Tests the VimureModel class with a known synthetic network

`class TestVimureWithReadData`

Tests the model with real data

### Methods

`def test_inform_nodes_reporters(self, karnataka_edgelist_vil1_money)`

# Index

* ### Super-module


	+ [`vimure.test`](vimure.index.html)
* ### [Functions](#header-functions)


	+ [`check_final_parameters`](vimure.#vimure.test.test_model.check_final_parameters)
* ### [Classes](#header-classes)


	+ #### [`TestInferredModel`](vimure.#vimure.test.test_model.TestInferredModel)
	
	
		- [`check_output`](vimure.#vimure.test.test_model.TestInferredModel.check_output)
		- [`setup_class`](vimure.#vimure.test.test_model.TestInferredModel.setup_class)
		- [`test_fixed_threshold`](vimure.#vimure.test.test_model.TestInferredModel.test_fixed_threshold)
		- [`test_heuristic_threshold`](vimure.#vimure.test.test_model.TestInferredModel.test_heuristic_threshold)
		- [`test_non_implemented_method`](vimure.#vimure.test.test_model.TestInferredModel.test_non_implemented_method)
		- [`test_rho_max`](vimure.#vimure.test.test_model.TestInferredModel.test_rho_max)
		- [`test_rho_mean`](vimure.#vimure.test.test_model.TestInferredModel.test_rho_mean)
		- [`test_sample_Y`](vimure.#vimure.test.test_model.TestInferredModel.test_sample_Y)
	+ #### [`TestVimureRealData`](vimure.#vimure.test.test_model.TestVimureRealData)
	
	
		- [`test_data_as_edgelist`](vimure.#vimure.test.test_model.TestVimureRealData.test_data_as_edgelist)
		- [`test_internal_api`](vimure.#vimure.test.test_model.TestVimureRealData.test_internal_api)
	+ #### [`TestVimureWithRandomNetworks`](vimure.#vimure.test.test_model.TestVimureWithRandomNetworks)
	
	
		- [`test_vimure_model_extreme_scenarios_over_reporting`](vimure.#vimure.test.test_model.TestVimureWithRandomNetworks.test_vimure_model_extreme_scenarios_over_reporting)
		- [`test_vimure_model_extreme_scenarios_over_reporting_dense`](vimure.#vimure.test.test_model.TestVimureWithRandomNetworks.test_vimure_model_extreme_scenarios_over_reporting_dense)
		- [`test_vimure_model_extreme_scenarios_under_reporting`](vimure.#vimure.test.test_model.TestVimureWithRandomNetworks.test_vimure_model_extreme_scenarios_under_reporting)
		- [`test_vimure_model_issues_appropriate_warnings`](vimure.#vimure.test.test_model.TestVimureWithRandomNetworks.test_vimure_model_issues_appropriate_warnings)
		- [`test_vimure_model_with_standard_sbm`](vimure.#vimure.test.test_model.TestVimureWithRandomNetworks.test_vimure_model_with_standard_sbm)
	+ #### [`TestVimureWithReadData`](vimure.#vimure.test.test_model.TestVimureWithReadData)
	
	
		- [`test_inform_nodes_reporters`](vimure.#vimure.test.test_model.TestVimureWithReadData.test_inform_nodes_reporters)

Generated by [pdoc 0.10.0](https://pdoc3.github.io/pdoc "pdoc: Python API documentation generator").

