---
title: "📚 Python package documentation"
subtitle: "VIMuRe v0.1 (latest)"
---
Module `vimure.test`

Unittests

## Sub-modules

[`vimure.test.test_generate_X`](vimure.test_generate_X.html)

[`vimure.test.test_io`](vimure.test_io.html)

[`vimure.test.test_model`](vimure.test_model.html)

[`vimure.test.test_synthetic`](vimure.test_synthetic.html)

## Functions

`def karnataka_edgelist_vil1()`

`def karnataka_edgelist_vil1_money()`

`def suppress_stdout_stderr()`

A context manager that redirects stdout and stderr to devnull
Source: <https://stackoverflow.com/a/52442331>

# Index

* ### Super-module


	+ [`vimure`](vimure.../index.html)
* ### [Sub-modules](#header-submodules)


	+ [`vimure.test.test_generate_X`](vimure.test_generate_X.html)
	+ [`vimure.test.test_io`](vimure.test_io.html)
	+ [`vimure.test.test_model`](vimure.test_model.html)
	+ [`vimure.test.test_synthetic`](vimure.test_synthetic.html)
* ### [Functions](#header-functions)


	+ [`karnataka_edgelist_vil1`](vimure.#vimure.test.karnataka_edgelist_vil1)
	+ [`karnataka_edgelist_vil1_money`](vimure.#vimure.test.karnataka_edgelist_vil1_money)
	+ [`suppress_stdout_stderr`](vimure.#vimure.test.suppress_stdout_stderr)

Generated by [pdoc 0.10.0](https://pdoc3.github.io/pdoc "pdoc: Python API documentation generator").

