---
title: "📚 Python package documentation"
subtitle: "VIMuRe v0.1 (latest)"
---
Module `vimure.diagnostics`

Diagnostics metrics

## Classes

`class Diagnostics
(model: [VimureModel](model.html#vimure.model.VimureModel "vimure.model.VimureModel") = None, net: [BaseSyntheticNetwork](synthetic.html#vimure.synthetic.BaseSyntheticNetwork "vimure.synthetic.BaseSyntheticNetwork") = None, verbose: bool = None)`

### Methods

`def plot_adjacency_matrix(self, layer, node_order=None, return_node_order=False, gradient_low='#fcfcfc', gradient_mid='#86cefa', gradient_high='#003396', hide_legend=False, include_ground_truth=True, additional_Ys={})`

Plot adjacency matrix of layer l, compared to ground truth

`def plot_baseline(self)`

`def plot_elbo_values(self)`

Plot the multiple realisations of ELBO values.

`def plot_pairs(self, params: dict = {})`

`def plot_posteriors(self, params: dict = {})`

`def plot_theta(self, theta_GT: numpy.ndarray = None, node_order: list = None, return_node_order: bool = False, return_plot_df: bool = False, remove_nodes: list = None)`

Scatterplot showing theta distribution (reporters' reciprocity),
compared to ground truth theta (theta_GT) when that is available

`def reliability_interactions(self, rep_id)`

# Index

* ### Super-module


	+ [`vimure`](vimure.index.html)
* ### [Classes](#header-classes)


	+ #### [`Diagnostics`](vimure.#vimure.diagnostics.Diagnostics)
	
	
		- [`plot_adjacency_matrix`](vimure.#vimure.diagnostics.Diagnostics.plot_adjacency_matrix)
		- [`plot_baseline`](vimure.#vimure.diagnostics.Diagnostics.plot_baseline)
		- [`plot_elbo_values`](vimure.#vimure.diagnostics.Diagnostics.plot_elbo_values)
		- [`plot_pairs`](vimure.#vimure.diagnostics.Diagnostics.plot_pairs)
		- [`plot_posteriors`](vimure.#vimure.diagnostics.Diagnostics.plot_posteriors)
		- [`plot_theta`](vimure.#vimure.diagnostics.Diagnostics.plot_theta)
		- [`reliability_interactions`](vimure.#vimure.diagnostics.Diagnostics.reliability_interactions)

Generated by [pdoc 0.10.0](https://pdoc3.github.io/pdoc "pdoc: Python API documentation generator").

