---
title: "📚 Python package documentation"
subtitle: "VIMuRe v0.1 (latest)"
---
Module `vimure.test.test_generate_X`

## Functions

`def check_objects(gt_network)`

Check tensor X

## Classes

`class TestGenerateXForStandardSBM`

### Methods

`def test_build_X_baselines_exist(self)`

Asserts that Union and Intersection baselines are produced and are correct after build_X is invoked

`def test_build_X_ensure_baselines_are_binary(self)`

Asserts that Union and Intersection baselines are produced and correct even when K is higher than 2


K represents the maximum entry value in the ground truth Y and it is also used by build_X to set Q
(if the user does not provide a value for Q).
With this test, we want to ensure that the baselines are still binary regardless of K.

`def test_build_X_param_cutoff_X_False(self)`

`def test_build_X_param_cutoff_X_True(self)`

`def test_build_X_with_different_seeds(self)`

Tests whether running the function without informing any particular seed
indeed leads to different tensors, guaranteeing that our code is not reusing seed parameters.

# Index

* ### Super-module


	+ [`vimure.test`](vimure.index.html)
* ### [Functions](#header-functions)


	+ [`check_objects`](vimure.#vimure.test.test_generate_X.check_objects)
* ### [Classes](#header-classes)


	+ #### [`TestGenerateXForStandardSBM`](vimure.#vimure.test.test_generate_X.TestGenerateXForStandardSBM)
	
	
		- [`test_build_X_baselines_exist`](vimure.#vimure.test.test_generate_X.TestGenerateXForStandardSBM.test_build_X_baselines_exist)
		- [`test_build_X_ensure_baselines_are_binary`](vimure.#vimure.test.test_generate_X.TestGenerateXForStandardSBM.test_build_X_ensure_baselines_are_binary)
		- [`test_build_X_param_cutoff_X_False`](vimure.#vimure.test.test_generate_X.TestGenerateXForStandardSBM.test_build_X_param_cutoff_X_False)
		- [`test_build_X_param_cutoff_X_True`](vimure.#vimure.test.test_generate_X.TestGenerateXForStandardSBM.test_build_X_param_cutoff_X_True)
		- [`test_build_X_with_different_seeds`](vimure.#vimure.test.test_generate_X.TestGenerateXForStandardSBM.test_build_X_with_different_seeds)

Generated by [pdoc 0.10.0](https://pdoc3.github.io/pdoc "pdoc: Python API documentation generator").

