---
title: "VIMuRe"
subtitle: "Latent Network Models to Account for Noisy, Multiply-Reported Social Network Data"
---

::: callout-note

The latest version (v0.1.3) simplifies the installation process for the R package. Check out the 📦 [Installation page](/latest/install.html) for more details. 

If you give it a go, [write to us](https://github.com/latentnetworks/vimure/discussions) if you have any questions or comments about the package!

If you want to see what we have planned for the future, check out the [Roadmap](https://github.com/latentnetworks/vimure/milestones?direction=asc&sort=title&state=open) on GitHub.

:::

# 📑 Is this package for me?

Suppose you want to find out the "true" network of social ties between $n$ individuals and you query $m$ "reporters" within this network (where $m \le n$) about such ties. These ties could, for instance, represent relationships commonly studied in the social sciences — such as loaning money, giving advice, or sharing food.

Suppose, also, that you ask them questions in both directions: "Who does person $i$ _borrow_ money _from_?" and "Who does person $i$ _lend_ money _to_?" As it is doubtful that the responses given by the reporters will match perfectly, you will almost surely end up with varying perspectives on what should be the same relationship and, so too, varying perspectives on the structure of the overall social network. The question then is, how do you make sense of this data in the face of inconsistent reports and potentially unreliable reporters?

The model in the **VIMuRe** package is our proposed solution to this problem. It fits a latent network model from multiply-sampled social network data using Bayesian inference, returning a posterior distribution that can later be used to obtain samples or a point-estimate network (e.g., as an igraph object). The package was written in Python and R and is available on GitHub (https://github.com/latentnetworks/vimure).

## 📝 In brief

- **Input:** multiply-sampled social network data as an edgelist or an igraph object.

- **Output:** a fitted latent network model that can be used to obtain samples or a point-estimate network (an igraph object) from the posterior distribution of the fitted model.

## Getting started

- Head to the 📦 [Installation](./latest/install.qmd) page to learn how to install the package (either R or Python).
- Check out the 💻 [Tutorials](./latest/tutorials.html) page to learn how to use the package.